image: debian

stages:
  - Mirror

github:
  stage: Mirror
  only:
    - master
  before_script:
    - apt update && apt -y install git
    - shopt -s extglob
  script:
    - rm -rf $HOME/gittmp
    - mkdir $HOME/gittmp
    - cp -rf * $HOME/gittmp
    - rm -rf $HOME/gittmp/.git
    - cd $HOME
    - git clone -- mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/frousselet/dotfiles.git
    - cd dotfiles
    - cp -rf $HOME/gittmp/* .
    - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/frousselet/dotfiles.git
