# @Author: François Rousselet <frousselet>
# @Date:   2017-02-26T13:53:56+01:00
# @Email:  francois@rousselet.info
# @Filename: Berksfile
# @Last modified by:   frousselet
# @Last modified time: 2017-02-26T13:56:01+01:00

site :opscode

cookbook 'apt'
cookbook 'apache2'
